/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: "tw-", // prefix for all utility classes
  content: [
    "./layout/**/*.liquid",
    "./templates/**/*.liquid",
    "./sections/**/*.liquid",
    "./snippets/**/*.liquid",
    "./assets/**/*.liquid",
    "./blocks/**/*.liquid",
  ],
  theme: {
    fontSize: {
      8: "0.5rem", // 8px
      10: "0.625rem", // 10px
      12: "0.75rem",
      14: "0.875rem",
      16: "1rem",
      18: "1.125rem",
      20: "1.25rem",
      22: "1.375rem",
      24: "1.5rem",
      26: "1.625rem",
      28: "1.75rem",
      30: "1.875rem",
      32: "2rem",
      36: "2.25rem",
      40: "2.5rem",
      44: "2.75rem",
      48: "3rem",
      52: "3.25rem",
      55: "3.4375rem",
      56: "3.5rem",
      60: "3.75rem",
      64: "4rem",
    },
    extend: {
      colors: {
        white: "#FFFFFF",
        black: "#000000",
        offblack: "#212121",
        brand: {
          primary: "#20448F",
          link: "#20448F",
          author: "#6F8BC5",
          secondary: "#F0BA3A",
          sale: "#BD2026",
          eggshell: "#FDFBF8",
          grey: "#CCCBC7",
        },
      },
      animation: {
        "fade-in": "fade 0.4s ease-in-out 1 forwards",
        "fade-out": "fadeout 0.4s ease-in-out 1 forwards",
        "fade-down": "fadeDown 0.5s ease-in-out 1 forwards",
      },
      leading: {
        'tighter': '1.1'
      },
      keyframes: {
        fade: {
          "0%": { opacity: 0 },
          "100%": { opacity: 100 },
        },
        fadeout: {
          "0%": { opacity: 100 },
          "100%": { opacity: 0 },
        },
        fadeDown: {
          "0%": {
            opacity: 0,
            transform: "translateY(-100%)",
          },
          "50%": {
            opacity: 0,
          },
          "100%": {
            opacity: 100,
            transform: "translateY(0%)",
          },
        },
      },
      transitionProperty: {
        button: "background-color, transform, border-color, color",
      },
      maxWidth: {
        "container-xl": "min(87.5rem, 90%)",
        "container-lg": "min(72.75rem, 90%)",
        "container-md": "min(65.25rem, 90%)",
        "container-sm": "min(43.125rem, 90%)",
        "screen-3xl": "1920px",
      },
      width: {
        "2/5": "40%",
        "3/5": "60%",
        "4/5": "80%",
      },
      maxHeight: {
        "container-xl": "min(87.5rem, 90%)",
        "container-lg": "min(72.75rem, 90%)",
        "container-md": "min(65.25rem, 90%)",
        "container-sm": "min(43.125rem, 90%)",
      },
      fontFamily: {
        'brand-header': ['"proxima-nova"', 'sans-serif'],
        'brand-body': ['"proxima-nova"', 'sans-serif'],
        montserrat: ['"proxima-nova"', 'sans-serif'],
        playfair: ['"proxima-nova"', 'sans-serif'],
        interstate: ['"proxima-nova"', 'sans-serif'],
        cadet: ['"proxima-nova"', 'sans-serif'],
        cadet_bold: ['"proxima-nova"', 'sans-serif'],
      },
      aspectRatio: {
        "1/2": "1 / 2",
        "2/1": "2 / 1",
        "2/3": "2 / 3",
        "3/2": "3 / 2",
        "3/4": "3 / 4",
        "4/3": "4 / 3",
        "5/4": "5 / 4",
        "4/5": "4 / 5",
        "3/5": "3 / 5",
        "5/3": "5 / 3",
        "3/7": "3 / 7",
        "5/6": "5 / 6",
        "6/5": "6 / 5",
        "6/7": "6 / 7",
        "7/6": "7 / 6",
        "9/10": "9 / 10",
        "10/9": "10 / 9",
        "3/8": "3 / 8",
        "8/3": "8 / 3",
        "9/16": "9 / 16",
        "16/9": "16 / 9",
      },
      typography: () => ({
        fr: {
          css: {
            '--tw-prose-body': 'var(--color-gray-950)',
            '--tw-prose-headings': 'var(--color-gray-950)',
            '--tw-prose-lead': 'var(--color-gray-950)',
            '--tw-prose-links': 'var(--color-gray-950)',
            '--tw-prose-bold': 'var(--color-gray-950)',
            '--tw-prose-counters': 'var(--color-gray-950)',
            '--tw-prose-bullets': 'var(--color-gray-950)',
            '--tw-prose-hr': 'var(--color-gray-950)',
            '--tw-prose-quotes': 'var(--color-gray-950)',
            '--tw-prose-quote-borders': 'var(--color-gray-950)',
            '--tw-prose-captions': 'var(--color-gray-950)',
            '--tw-prose-code': 'var(--color-gray-950)',
            '--tw-prose-pre-code': 'var(--color-gray-950)',
            '--tw-prose-pre-bg': 'var(--color-gray-950)',
            '--tw-prose-th-borders': 'var(--color-gray-950)',
            '--tw-prose-td-borders': 'var(--color-gray-950)',
            '--tw-prose-invert-body': 'var(--color-gray-50)',
            '--tw-prose-invert-headings': 'var(--color-white)',
            '--tw-prose-invert-lead': 'var(--color-gray-50)',
            '--tw-prose-invert-links': 'var(--color-white)',
            '--tw-prose-invert-bold': 'var(--color-white)',
            '--tw-prose-invert-counters': 'var(--color-gray-50)',
            '--tw-prose-invert-bullets': 'var(--color-gray-50)',
            '--tw-prose-invert-hr': 'var(--color-gray-50)',
            '--tw-prose-invert-quotes': 'var(--color-gray-50)',
            '--tw-prose-invert-quote-borders': 'var(--color-gray-50)',
            '--tw-prose-invert-captions': 'var(--color-gray-50)',
            '--tw-prose-invert-code': 'var(--color-white)',
            '--tw-prose-invert-pre-code': 'var(--color-gray-50)',
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': 'var(--color-gray-50)',
            '--tw-prose-invert-td-borders': 'var(--color-gray-50)',
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
